### PR TITLE
Make prisms work

### PR DESCRIPTION
**Pull request by ghost**
This is still a work in progress, but I wanted to make prisms actual prisms, because it seemed a shame that they weren't.  This involves making a wrapper around (->) which I called Arrow, in `Data.Profunctor.Arrow`.  All optics now use this type rather than functions, and since it can have a `Choice` implementation, prisms now just work!

Except they don't.  The examples using prisms now fail, which I will try to fix.  Could you also have a look at why they are failing, please?

It is no longer true that a user can write a lens without incurring any dependencies, to the long term plan would be to move Data.Profunctor.Arrow into its own tiny package, called `arrow-profunctor` or something.  Then users would only have to depend on that, not the lens library, to write lenses.  Hence this module also has the helpful `lens` function.

Cheers,
Tom

### CODE REVIEW

**Comment by ghost** [comment]
OK, the examples just needed a bit more help with type inference.

Ready to merge when you're happy, then.

**Comment by HuwCampbell** [comment]
G'day
Thanks for this, looks really good.

I was thinking about doing something similar, and if I were to ask for a change to be more in line with what I had planned, it would be to use the standard library's [MonadReader](https://github.com/idris-lang/Idris-dev/blob/master/libs/base/Control/Monad/Reader.idr) (which has `Reader` on Identity) instead of your `Arrow`. This would change `view` to take a `MonadReader`, but it would probably make it more like `Control.Lens`'s [version](https://github.com/ekmett/lens/blob/15a94d8c36fa47e5ba1956a8720a1a1cd0b99c58/src/Control/Lens/Getter.hs#L253)

I'm pretty sure it should work, and am happy to have a look at doing this tonight or tomorrow if you don't have the time.

**Comment by ghost** [comment]
Sounds good!  I'll change that soon then.

**Comment by ghost** [comment]
I'm imagining a Profunctor instance for (`ReaderT` r f a) whenever f is a functor, except that the type variables are in the wrong positions for the Profunctor class.  Does that mean I need a wrapper around `ReaderT` to swap `m` with `r`?

**Comment by HuwCampbell** [comment]
I don't think you can do one for `ReaderT`, only `Reader` (on Identity).
How about we park that change for another PR and merge these two in now?

I think my suggestion is doable (and would give a good instance for MonadReader which would make Getter nicer), but it's better to get the ball rolling I think.

**Comment by ghost** [comment]
I'm up for merging now, but I don't understand how to make an instance for Reader.  I get an error saying "Implementation arguments must be injective", which makes sense because Reader is essentially a type synonym.  Should you be able to make an implementation for Reader in Idris?

**Comment by HuwCampbell** [comment]
I got the same error when I tried, so it looks like not.
Merged in.
Thanks!

**Pull request merged**
